---
- name: Converge
  hosts: all
  gather_facts: true
  become: false

  vars:
    packages_install_onepassword: true
    packages_install_github_cli: true
    packages_install_claude_code: true
    packages_install_cursor_agent: true
    packages_install_extra_packages: true
    packages_install_nodejs_pinned: true

  roles:
    - role: david_igou.devhost.packages
