---
dependency:
  name: galaxy
  options:
    requirements-file: extensions/molecule/provisioners/${PROVISIONER:-podman}/requirements.yml
    force: true
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: devhost-packages-ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
    command: sleep 1d
    namespace: ${MOLECULE_NAMESPACE:-ci-devhost}
  - name: devhost-packages-centos
    image: quay.io/centos/centos:stream10
    command: sleep 1d
    namespace: ${MOLECULE_NAMESPACE:-ci-devhost}
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    create: ../provisioners/${PROVISIONER:-podman}/create.yml
    destroy: ../provisioners/${PROVISIONER:-podman}/destroy.yml
    prepare: ../provisioners/${PROVISIONER:-podman}/prepare.yml
    verify: verify.yml
  inventory:
    links:
      group_vars: ../provisioners/${PROVISIONER:-podman}/group_vars/
verifier:
  name: ansible
scenario:
  name: packages
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
