---
podman_rootless_subuid_start: 100000
podman_rootless_subuid_count: 65536
podman_rootless_user_namespaces_max: 28633
podman_rootless_unprivileged_port_start: 0
podman_rootless_socket_symlink: true
podman_rootless_enable_linger: true

podman_rootless_configure_containers_conf: true
podman_rootless_events_logger: "file"

podman_rootless_configure_storage_conf: false
podman_rootless_storage_driver: "overlay"
podman_rootless_storage_mount_program: "/usr/bin/fuse-overlayfs"
