---
packages_install_onepassword: true
packages_install_github_cli: true
packages_install_claude_code: true
packages_install_cursor_agent: true

# renovate: datasource=npm depName=@devcontainers/cli
packages_devcontainer_cli_version: "0.85.0"
