---
- name: Create VM dictionary
  vars:
    __kubevirt_ssh_service_port: >-
      {%- set svc_type = vm.kubevirt.ssh_service.type | default(None) -%}
      {%- if svc_type == 'NodePort' -%}
        {{ (__kubevirt_node_port_services.results
            | selectattr('vm.name', '==', vm.name)
            | first)['resources'][0]['spec']['ports'][0]['nodePort'] }}
      {%- endif -%}
  ansible.builtin.set_fact:
    __kubevirt_molecule_systems: >-
      {{
        __kubevirt_molecule_systems | default({}) | combine({
          vm.name: {
            'ansible_user': vm.kubevirt.ansible_user,
            'ansible_host': __kubevirt_nodeport_host,
            'ansible_ssh_port': __kubevirt_ssh_service_port,
            'ansible_ssh_private_key_file': __kubevirt_ssh_key_path
          }
        })
      }}
