---
- name: Converge
  hosts: all
  gather_facts: true
  become: false

  vars:
    podman_docker_compat: false
    podman_docker_socket_symlink: false

  pre_tasks:
    - name: Wait for cloud-init to finish
      ansible.builtin.command:
        cmd: cloud-init status --wait
      changed_when: false
      become: true
      failed_when: false

  roles:
    - role: david_igou.devhost.podman
    - role: david_igou.devhost.docker
