---
driver:
  name: default
  options:
    managed: false
platforms:
  - name: localhost
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: podman_rootless
  test_sequence:
    - syntax
