---
dependency:
  name: galaxy
  options:
    requirements-file: extensions/molecule/provisioners/${PROVISIONER:-podman}/requirements.yml
    force: true
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: devhost-host-prep-ubuntu
    podman:
      image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
      command: sleep 1d
    kubevirt:
      image: registry.redhat.io/rhel9/rhel-guest-image
      namespace: ${MOLECULE_NAMESPACE:-ci-devhost}
      ssh_service:
        type: NodePort
      ansible_user: cloud-user
      memory: 1Gi
  - name: devhost-host-prep-centos
    podman:
      image: quay.io/centos/centos:stream10
      command: sleep 1d
    kubevirt:
      image: registry.redhat.io/rhel9/rhel-guest-image
      namespace: ${MOLECULE_NAMESPACE:-ci-devhost}
      ssh_service:
        type: NodePort
      ansible_user: cloud-user
      memory: 1Gi
  - name: devhost-host-prep-fedora
    podman:
      image: docker.io/geerlingguy/docker-fedora43-ansible:latest
      command: sleep 1d
    kubevirt:
      image: quay.io/containerdisks/fedora:latest
      namespace: ${MOLECULE_NAMESPACE:-ci-devhost}
      ssh_service:
        type: NodePort
      ansible_user: cloud-user
      memory: 1Gi
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    create: ../provisioners/${PROVISIONER:-podman}/create.yml
    destroy: ../provisioners/${PROVISIONER:-podman}/destroy.yml
    prepare: ../provisioners/${PROVISIONER:-podman}/prepare.yml
    verify: verify.yml
  inventory:
    links:
      group_vars: ../provisioners/${PROVISIONER:-podman}/group_vars/
verifier:
  name: ansible
scenario:
  name: host_prep
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
