---
- name: Add Docker CE yum repository
  vars:
    __docker_distro: "{{ 'fedora' if ansible_facts.distribution == 'Fedora' else 'centos' }}"
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable
    baseurl: "https://download.docker.com/linux/{{ __docker_distro }}/$releasever/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: true
    enabled: true

- name: Remove podman-docker to avoid conflict
  ansible.builtin.dnf:
    name: podman-docker
    state: absent

- name: Install docker-ce-cli
  ansible.builtin.dnf:
    name: docker-ce-cli
    state: present
  when: docker_install_cli

- name: Install docker-compose-plugin
  ansible.builtin.dnf:
    name: docker-compose-plugin
    state: present
  when: docker_install_compose_plugin

- name: Install Docker daemon packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - containerd.io
    state: present
  when: docker_install_daemon

- name: Install rootless Docker extras
  ansible.builtin.dnf:
    name: docker-ce-rootless-extras
    state: present
  when: docker_rootless
