---
- name: Provision development host
  hosts: devhosts
  gather_facts: true
  roles:
    - role: david_igou.devhost.packages
    - role: david_igou.devhost.host_prep
    - role: david_igou.devhost.podman
    - role: david_igou.devhost.docker
