---
name: Release david_igou.devhost

on: # yamllint disable-line rule:truthy
  release:
    types: [published]
jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@05894f1a7922836072b5a12e80f9c2ed5f489567 # main
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
