---
name: Release david_igou.devhost

on: # yamllint disable-line rule:truthy
  release:
    types: [published]
jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@11fc6c1c1a2421cac44cc5c40b6f72656745f1f9 # main
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
