---
name: Release david_igou.devhost

on: # yamllint disable-line rule:truthy
  release:
    types: [published]
jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@dc47efd46c312b6ffaf10c274825707a65ac1d86 # main
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
